export const Cards_Object = [
    { id: 1, title: 'Mauro Henrique'},
    { id: 2, title: 'Estevão Queiroga'},
    { id: 3, title: 'Guilherme Iamarino'},
    { id: 4, title: 'Guilherme Andrade'},
    { id: 5, title: 'EscatoLove'},
    { id: 6, title: 'Rosas de Saron'},
    { id: 7, title: 'Marcos Almeida'},
    { id: 8, title: 'Os Arrais'},
    { id: 9, title: 'Purples'},
    { id: 10, title: 'IPHALPA'},
    { id: 12, title: 'Oficina G3'},
    { id: 13, title: 'Baruk'},
    { id: 14, title: 'Leonardo Gonçalves'},
    { id: 15, title: 'Vocal Livre'},
    { id: 16, title: 'Gabriel Guedes'},
    { id: 17, title: 'Resgate'},
]